# Generated by Django 3.0.5 on 2021-12-10 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainPizza', '0002_topping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainPizza.Pizza'),
        ),
    ]
