# Generated by Django 3.0.5 on 2021-12-10 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainPizza', '0005_auto_20211209_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainPizza.Pizza'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topping',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainPizza.Pizza'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
